# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-alb
  description: This component is responsible for provisioning a generic Application Load Balancer
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component

